#!/usr/bin/env node
/*
 * Copyright (c) 2026 Ezra Brilliant Konterliem
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

/*
 * Writes docs/commands.md from POST /describe_commands of the running
 * StarUML: the catalogue in src/command-catalogue.json (read from the app
 * sources) joined with the ids registered in this session, so the table also
 * shows commands added by installed extensions and catalogued commands that
 * are not loaded. Re-run after StarUML, the catalogue or the installed
 * extensions change:
 *
 *   npm run docs:commands
 *
 * Environment: STARUML_EXT_URL (default http://localhost:58322),
 * STARUML_EXT_TOKEN when StarUML requires an access token.
 */
import { writeFileSync } from "node:fs";
import { format } from "prettier";

const base = process.env.STARUML_EXT_URL ?? "http://localhost:58322";
const res = await fetch(`${base}/describe_commands`, {
  method: "POST",
  headers: {
    "Content-Type": "application/json",
    ...(process.env.STARUML_EXT_TOKEN && {
      Authorization: `Bearer ${process.env.STARUML_EXT_TOKEN}`,
    }),
  },
  body: "{}",
});
const body = await res.json();
if (!body.success) {
  console.error(`describe_commands failed: ${JSON.stringify(body)}`);
  process.exit(1);
}
const { catalogue, commands } = body.data;
const cell = (text) =>
  (text ?? "").replaceAll("|", "\\|").replaceAll("\n", " ");
const args = (c) =>
  !c.args
    ? "?"
    : c.args.length === 0
      ? "none"
      : c.args
          .map(
            (a) =>
              `\`${a.name}${a.optional ? "?" : ""}\`: ${a.type}${a.note ? `. ${a.note}` : ""}`,
          )
          .join("<br>");
const dialog = (c) =>
  c.dialog === "without-args" ? `without-args (${c.avoidWith})` : c.dialog;
const counts = {};
for (const c of commands) counts[c.dialog] = (counts[c.dialog] ?? 0) + 1;

const lines = [
  "# StarUML commands",
  "",
  `Generated by \`npm run docs:commands\` from \`POST /describe_commands\` against StarUML ${catalogue}; do not edit by hand. The catalogue (\`src/command-catalogue.json\`) was read from each command's handler in the app sources; *registered* is what the running app had loaded when this file was written.`,
  "",
  'Run a command with `POST /execute_command {"id": ..., "args": [...]}`. Arguments are positional; elements are passed as ids only where a command takes a string, so commands taking an `Element` are best reached through the dedicated endpoints.',
  "",
  "## Dialogs",
  "",
  "`/execute_command` answers `DIALOG_REQUIRED` (422) instead of hanging:",
  "",
  "- **always**: opens a dialog whatever it is given; refused before it runs.",
  "- **without-args (n)**: opens a dialog unless given its first n arguments; refused when fewer are passed.",
  "- **confirm**: may open a dialog depending on state (unsaved changes, selection, clipboard). It runs with every dialog entry point of `app.dialogs` and the `app.*Dialog.showDialog` pickers replaced, and is stopped where a dialog would open.",
  "- **external**: opens a URL in the system browser.",
  "- **unknown**: not in the catalogue (another extension); it runs under the same dialog guard as *confirm*.",
  "",
  Object.entries(counts)
    .sort()
    .map(([k, v]) => `${k}: ${v}`)
    .join(", ") + ".",
  "",
  "Dedicated endpoints cover the common dialog-bound commands: `/save_project_as`, `/open_project`, `/export_diagram`, `/export_diagrams`, `/export_pdf`, `/export_html`, `/generate_code`, `/reverse_code`.",
  "",
  "## Commands",
  "",
  "| Command | Registered | Dialog | Arguments | Effect | Needs | Source |",
  "| --- | --- | --- | --- | --- | --- | --- |",
  ...commands.map(
    (c) =>
      `| \`${c.id}\` | ${c.registered ? "yes" : "no"} | ${dialog(c)} | ${cell(args(c))} | ${cell([c.effect, c.note].filter(Boolean).join(" "))} | ${cell(c.needs)} | ${cell(c.source)} |`,
  ),
  "",
];
const file = new URL("../docs/commands.md", import.meta.url);
writeFileSync(file, await format(lines.join("\n"), { parser: "markdown" }));
console.log(`wrote ${file.pathname} (${commands.length} commands)`);
